import java.math.RoundingMode;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Radio.java
//  @ Date : 1/16/2023
//  @ Author : 
//
//




public class Radio implements IRadio {
	private String freq;
	private double actualStationFM;
	private int actualStationAM;
	private String estado;
	private ArrayList<Double> emisorasFM = new ArrayList<Double>();
	private ArrayList<Integer> emisorasAM = new ArrayList<Integer>();
	//private int actualStation;
	private int slot;
	@Override
	public void on(){
		estado = "on";
	}
	@Override
	public void off(){
		estado = "off";
	}
	@Override
	public boolean isOn() {
		if(estado=="on"){
			return true;
		}else{
			return false;
		}
		
	}
	@Override
	public void setFrequence(String freq) {//throws Exception {//**
		this.freq=freq;
		
	}
	@Override
	public String getFrequence() {
		return freq;
	}
	@Override
	public void Forward() {//**
		if(freq=="AM"){
			

		}
		else if(freq=="FM"){
			if(actualStationFM==107.9){
				actualStationFM=87.9;

			}
			else{
				actualStationFM=actualStationFM+0.2;
				actualStationFM=Math.round((actualStationFM) * 10) / 10.0;
			}
		}
		else{

		}
	}
	@Override
	public void Backward() {//**
		if(freq=="AM"){
			

		}
		else if(freq=="FM"){
			if(actualStationFM==87.9){
				actualStationFM=107.9;
				

			}
			else{
				actualStationFM=actualStationFM-0.2;
				actualStationFM=Math.round((actualStationFM) * 10) / 10.0;
			}
		}
		else{

		}
	}
	@Override
	public double getFMActualStation() {
		return actualStationFM;
	}
	@Override
	public int getAMActualStation() {//**
		return actualStationAM;
	}
	@Override
	public void setFMActualStation(double actualStation) {
		this.actualStationFM = actualStation;
	}
	@Override
	public void setAMActualStation(int actualStation) {//**
		this.actualStationAM= actualStation;
	}
	@Override
	public void saveFMStation(double actualStation, int slot) {//**
		if(emisorasFM.size()<=12){
			emisorasFM.add(actualStation);
		}
	}
	@Override
	public void saveAMStation(int actualStation, int slot) {//** 
		if(emisorasAM.size()<=12){
			emisorasAM.add(actualStation);
		}
	}

	//Selecciona la emisora en el slot deseado FM
	@Override
	public double getFMSlot(int slot) {
		actualStationFM= emisorasFM.get(slot);
		return emisorasFM.get(slot);
	}

	//Selecciona la emisora en el slot deseado AM
	@Override
	public int getAMSlot(int slot) {//** 
		return emisorasAM.get(slot);
	}
	
	public Radio() {
		freq="AM";
		slot=0;
		actualStationFM=87.9;
		estado="off";
	}
	
	public Radio(String freq, int slot, double actualStation, String estado) {
		this.freq=freq;
		this.slot=slot;
		this.actualStationFM=actualStation;
		this.estado=estado;
	}
	
	
}
